#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade HG on Mon Aug 22 14:08:14 2011 from "D:\pasha\devel\sandbox\xrc\pyFuncGen\pyfuncgen.wxg"

import wx
import wx.grid

# begin wxGlade: extracode
# end wxGlade



class FuncGenFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FuncGenFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.mainPnl = wx.Panel(self, -1)
        self.devListRefreshBtn = wx.Button(self.mainPnl, wx.ID_REFRESH, "")
        self.deviceChoice = wx.Choice(self.mainPnl, -1, choices=[])
        self.connectBtn = wx.ToggleButton(self.mainPnl, -1, "connect")
        self.manualPnl = wx.Panel(self.mainPnl, -1)
        self.protocolGrid = wx.grid.Grid(self.mainPnl, -1, size=(1, 1))
        self.addRowBtn = wx.Button(self.mainPnl, wx.ID_ADD, "")
        self.cleanRowsBtn = wx.Button(self.mainPnl, wx.ID_DELETE, "")
        self.opeFileBtn = wx.Button(self.mainPnl, wx.ID_OPEN, "")
        self.saveFileBtn = wx.Button(self.mainPnl, wx.ID_SAVE, "")
        self.startBtn = wx.Button(self.mainPnl, -1, "START")
        self.pauseBtn = wx.ToggleButton(self.mainPnl, -1, "PAUSE")
        self.stopBtn = wx.Button(self.mainPnl, -1, "STOP")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnDevListRefresh, self.devListRefreshBtn)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.OnToggleConnect, self.connectBtn)
        self.Bind(wx.EVT_BUTTON, self.OnAddRow, self.addRowBtn)
        self.Bind(wx.EVT_BUTTON, self.OnCleanRows, self.cleanRowsBtn)
        self.Bind(wx.EVT_BUTTON, self.OnOpenFile, self.opeFileBtn)
        self.Bind(wx.EVT_BUTTON, self.OnSaveFile, self.saveFileBtn)
        self.Bind(wx.EVT_BUTTON, self.OnStart, self.startBtn)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.OnTogglePause, self.pauseBtn)
        self.Bind(wx.EVT_BUTTON, self.OnStop, self.stopBtn)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: FuncGenFrame.__set_properties
        self.SetTitle("pyFuncGen")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: FuncGenFrame.__do_layout
        mainHsizer = wx.BoxSizer(wx.HORIZONTAL)
        mainVsizer = wx.BoxSizer(wx.VERTICAL)
        protocolCtrlsizer = wx.BoxSizer(wx.HORIZONTAL)
        gridCtrlsizer = wx.BoxSizer(wx.HORIZONTAL)
        devCtrlsizer = wx.BoxSizer(wx.HORIZONTAL)
        devCtrlsizer.Add(self.devListRefreshBtn, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        devCtrlsizer.Add(self.deviceChoice, 1, wx.EXPAND, 0)
        devCtrlsizer.Add(self.connectBtn, 0, 0, 0)
        mainVsizer.Add(devCtrlsizer, 0, wx.EXPAND, 0)
        mainVsizer.Add(self.manualPnl, 0, 0, 0)
        mainVsizer.Add(self.protocolGrid, 1, wx.EXPAND, 0)
        gridCtrlsizer.Add(self.addRowBtn, 1, wx.EXPAND, 0)
        gridCtrlsizer.Add(self.cleanRowsBtn, 1, wx.EXPAND, 0)
        gridCtrlsizer.Add(self.opeFileBtn, 1, wx.EXPAND, 0)
        gridCtrlsizer.Add(self.saveFileBtn, 1, wx.EXPAND, 0)
        mainVsizer.Add(gridCtrlsizer, 0, wx.EXPAND, 0)
        protocolCtrlsizer.Add(self.startBtn, 1, wx.EXPAND, 0)
        protocolCtrlsizer.Add(self.pauseBtn, 1, wx.EXPAND, 0)
        protocolCtrlsizer.Add(self.stopBtn, 1, wx.EXPAND, 0)
        mainVsizer.Add(protocolCtrlsizer, 0, wx.EXPAND, 0)
        self.mainPnl.SetSizer(mainVsizer)
        mainHsizer.Add(self.mainPnl, 1, wx.EXPAND, 0)
        self.SetSizer(mainHsizer)
        mainHsizer.Fit(self)
        self.Layout()
        # end wxGlade

    def OnDevListRefresh(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnDevListRefresh' not implemented!"
        event.Skip()

    def OnToggleConnect(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnToggleConnect' not implemented!"
        event.Skip()

    def OnAddRow(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnAddRow' not implemented!"
        event.Skip()

    def OnCleanRows(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnCleanRows' not implemented!"
        event.Skip()

    def OnOpenFile(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnOpenFile' not implemented!"
        event.Skip()

    def OnSaveFile(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnSaveFile' not implemented!"
        event.Skip()

    def OnStart(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnStart' not implemented!"
        event.Skip()

    def OnTogglePause(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnTogglePause' not implemented!"
        event.Skip()

    def OnStop(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnStop' not implemented!"
        event.Skip()

# end of class FuncGenFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    MyFrame = FuncGenFrame(None, -1, "")
    app.SetTopWindow(MyFrame)
    MyFrame.Show()
    app.MainLoop()
