#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade HG on Wed Aug 24 09:14:10 2011 from "D:\pasha\devel\pyFuncGen\pyfuncgen.wxg"

import wx
import wx.grid

# begin wxGlade: extracode
import wx.lib.agw.floatspin as FS
import wx.lib.agw.floatspin as FS
# end wxGlade



class FuncGenFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FuncGenFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.mainPnl = wx.Panel(self, -1)
        self.devListRefreshBtn = wx.Button(self.mainPnl, wx.ID_REFRESH, "")
        self.deviceChoice = wx.Choice(self.mainPnl, -1, choices=[])
        self.connectBtn = wx.ToggleButton(self.mainPnl, -1, "connect")
        self.amplCtrl = FS.FloatSpin(self.mainPnl, -1)
        self.applyBtn = wx.Button(self.mainPnl, -1, "Apply")
        self.freqCtrlLabel = wx.StaticText(self.mainPnl, -1, "Frequency (Hz)")
        self.freqCtrl = FS.FloatSpin(self.mainPnl, -1)
        self.toggleOutputBtn = wx.ToggleButton(self.mainPnl, -1, "Output ON")
        self.freqDispLabel = wx.StaticText(self.mainPnl, -1, "Frequency")
        self.stageDisplay = wx.StaticText(self.mainPnl, -1, "---")
        self.amplDisplay = wx.StaticText(self.mainPnl, -1, "--- Vpp")
        self.freqDisplay = wx.StaticText(self.mainPnl, -1, "--- Hz")
        self.timeDisplay = wx.StaticText(self.mainPnl, -1, "--:--")
        self.protocolGrid = wx.grid.Grid(self.mainPnl, -1, size=(1, 1))
        self.addRowBtn = wx.Button(self.mainPnl, wx.ID_ADD, "")
        self.cleanRowsBtn = wx.Button(self.mainPnl, wx.ID_DELETE, "")
        self.openFileBtn = wx.Button(self.mainPnl, wx.ID_OPEN, "")
        self.saveFileBtn = wx.Button(self.mainPnl, wx.ID_SAVE, "")
        self.startBtn = wx.Button(self.mainPnl, -1, "START")
        self.pauseBtn = wx.ToggleButton(self.mainPnl, -1, "PAUSE")
        self.stopBtn = wx.Button(self.mainPnl, -1, "STOP")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnDevListRefresh, self.devListRefreshBtn)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.OnToggleConnect, self.connectBtn)
        self.Bind(wx.EVT_BUTTON, self.OnApply, self.applyBtn)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.OnToggleOutput, self.toggleOutputBtn)
        self.Bind(wx.EVT_BUTTON, self.OnAddRow, self.addRowBtn)
        self.Bind(wx.EVT_BUTTON, self.OnCleanRows, self.cleanRowsBtn)
        self.Bind(wx.EVT_BUTTON, self.OnOpenFile, self.openFileBtn)
        self.Bind(wx.EVT_BUTTON, self.OnSaveFile, self.saveFileBtn)
        self.Bind(wx.EVT_BUTTON, self.OnStart, self.startBtn)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.OnTogglePause, self.pauseBtn)
        self.Bind(wx.EVT_BUTTON, self.OnStop, self.stopBtn)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: FuncGenFrame.__set_properties
        self.SetTitle("pyFuncGen")
        self.stopBtn.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: FuncGenFrame.__do_layout
        mainHsizer = wx.BoxSizer(wx.HORIZONTAL)
        mainVsizer = wx.BoxSizer(wx.VERTICAL)
        protocolCtrlsizer = wx.BoxSizer(wx.HORIZONTAL)
        gridCtrlsizer = wx.BoxSizer(wx.HORIZONTAL)
        displaySizer = wx.GridSizer(2, 4, 1, 1)
        manualCtrlSizer = wx.GridSizer(2, 3, 1, 1)
        devCtrlsizer = wx.BoxSizer(wx.HORIZONTAL)
        devCtrlsizer.Add(self.devListRefreshBtn, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        devCtrlsizer.Add(self.deviceChoice, 1, wx.EXPAND, 0)
        devCtrlsizer.Add(self.connectBtn, 0, 0, 0)
        mainVsizer.Add(devCtrlsizer, 0, wx.EXPAND, 0)
        voltCtrlLabel = wx.StaticText(self.mainPnl, -1, "Amplitude (Vpp)")
        manualCtrlSizer.Add(voltCtrlLabel, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        manualCtrlSizer.Add(self.amplCtrl, 1, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        manualCtrlSizer.Add(self.applyBtn, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        manualCtrlSizer.Add(self.freqCtrlLabel, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        manualCtrlSizer.Add(self.freqCtrl, 1, wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 0)
        manualCtrlSizer.Add(self.toggleOutputBtn, 0, wx.ALIGN_RIGHT|wx.ALIGN_CENTER_VERTICAL, 0)
        mainVsizer.Add(manualCtrlSizer, 0, wx.EXPAND, 0)
        stageDispLabel = wx.StaticText(self.mainPnl, -1, "stage")
        displaySizer.Add(stageDispLabel, 0, 0, 0)
        amplDispLabel = wx.StaticText(self.mainPnl, -1, "Amplitude")
        displaySizer.Add(amplDispLabel, 0, 0, 0)
        displaySizer.Add(self.freqDispLabel, 0, 0, 0)
        timeDispLabel = wx.StaticText(self.mainPnl, -1, "Time remains")
        displaySizer.Add(timeDispLabel, 0, 0, 0)
        displaySizer.Add(self.stageDisplay, 0, 0, 0)
        displaySizer.Add(self.amplDisplay, 0, 0, 0)
        displaySizer.Add(self.freqDisplay, 0, 0, 0)
        displaySizer.Add(self.timeDisplay, 0, 0, 0)
        mainVsizer.Add(displaySizer, 0, wx.EXPAND, 0)
        mainVsizer.Add(self.protocolGrid, 1, wx.EXPAND, 0)
        gridCtrlsizer.Add(self.addRowBtn, 1, wx.EXPAND, 0)
        gridCtrlsizer.Add(self.cleanRowsBtn, 1, wx.EXPAND, 0)
        gridCtrlsizer.Add(self.openFileBtn, 1, wx.EXPAND, 0)
        gridCtrlsizer.Add(self.saveFileBtn, 1, wx.EXPAND, 0)
        mainVsizer.Add(gridCtrlsizer, 0, wx.EXPAND, 0)
        protocolCtrlsizer.Add(self.startBtn, 1, wx.EXPAND, 0)
        protocolCtrlsizer.Add(self.pauseBtn, 1, wx.EXPAND, 0)
        protocolCtrlsizer.Add(self.stopBtn, 1, wx.EXPAND, 0)
        mainVsizer.Add(protocolCtrlsizer, 0, wx.EXPAND, 0)
        self.mainPnl.SetSizer(mainVsizer)
        mainHsizer.Add(self.mainPnl, 1, wx.EXPAND, 0)
        self.SetSizer(mainHsizer)
        mainHsizer.Fit(self)
        self.Layout()
        # end wxGlade

    def OnDevListRefresh(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnDevListRefresh' not implemented!"
        event.Skip()

    def OnToggleConnect(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnToggleConnect' not implemented!"
        event.Skip()

    def OnApply(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnApply' not implemented!"
        event.Skip()

    def OnToggleOutput(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnToggleOutput' not implemented!"
        event.Skip()

    def OnAddRow(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnAddRow' not implemented!"
        event.Skip()

    def OnCleanRows(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnCleanRows' not implemented!"
        event.Skip()

    def OnOpenFile(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnOpenFile' not implemented!"
        event.Skip()

    def OnSaveFile(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnSaveFile' not implemented!"
        event.Skip()

    def OnStart(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnStart' not implemented!"
        event.Skip()

    def OnTogglePause(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnTogglePause' not implemented!"
        event.Skip()

    def OnStop(self, event): # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnStop' not implemented!"
        event.Skip()

# end of class FuncGenFrame


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    MyFrame = FuncGenFrame(None, -1, "")
    app.SetTopWindow(MyFrame)
    MyFrame.Show()
    app.MainLoop()
