#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.4 on Wed Oct 24 12:59:43 2012

import wx
import wx.grid

# begin wxGlade: extracode
import wx.lib.agw.floatspin as FS
import wx.lib.agw.floatspin as FS
# end wxGlade


class FuncGenFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: FuncGenFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.mainPnl = wx.Panel(self, -1)
        self.devListRefreshBtn = wx.Button(self.mainPnl, wx.ID_REFRESH, "")
        self.deviceChoice = wx.Choice(self.mainPnl, -1, choices=[])
        self.connectBtn = wx.ToggleButton(self.mainPnl, -1, "Connect")
        self.stageDisplay = wx.StaticText(self.mainPnl, -1, "---")
        self.freqCtrlLabel = wx.StaticText(self.mainPnl, -1, "Frequency (Hz)")
        self.freqCtrl = FS.FloatSpin(self.mainPnl, -1)
        self.applyBtn = wx.Button(self.mainPnl, -1, "Apply")
        self.timeDisplay = wx.StaticText(self.mainPnl, -1, "--:--")
        self.amplCtrl = FS.FloatSpin(self.mainPnl, -1)
        self.toggleOutputBtn = wx.ToggleButton(self.mainPnl, -1, "Output ON")
        self.intervalDispLabel = wx.StaticText(self.mainPnl, -1, "Update interval")
        self.intervalDisplay = wx.StaticText(self.mainPnl, -1, "---")
        self.amplVrmsDisplay = wx.StaticText(self.mainPnl, -1, "--- Vrms")
        self.pulseCtrl = wx.SpinCtrl(self.mainPnl, -1, "500", min=0, max=1000, style=wx.SP_ARROW_KEYS | wx.TE_AUTO_URL)
        self.pulseBtn = wx.Button(self.mainPnl, -1, "PULSE!")
        self.ctrlBoxSzr_staticbox = wx.StaticBox(self.mainPnl, -1, "Manual Controls")
        self.protocolGrid = wx.grid.Grid(self.mainPnl, -1, size=(1, 1))
        self.addRowBtn = wx.Button(self.mainPnl, wx.ID_ADD, "")
        self.cleanRowsBtn = wx.Button(self.mainPnl, wx.ID_DELETE, "")
        self.openFileBtn = wx.Button(self.mainPnl, wx.ID_OPEN, "")
        self.saveFileBtn = wx.Button(self.mainPnl, wx.ID_SAVE, "")
        self.protocolGridSzr_staticbox = wx.StaticBox(self.mainPnl, -1, "Protocol")
        self.startBtn = wx.Button(self.mainPnl, -1, "START")
        self.pauseBtn = wx.ToggleButton(self.mainPnl, -1, "PAUSE")
        self.stopBtn = wx.Button(self.mainPnl, -1, "STOP")
        self.leaveOutPauseCb = wx.CheckBox(self.mainPnl, -1, "Leave Output ON when paused")
        self.leaveOutFinishCb = wx.CheckBox(self.mainPnl, -1, "Leave Output ON when finished")
        self.protocolOptnsSzr_staticbox = wx.StaticBox(self.mainPnl, -1, "Options")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.OnDevListRefresh, self.devListRefreshBtn)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.OnToggleConnect, self.connectBtn)
        self.Bind(wx.EVT_BUTTON, self.OnApply, self.applyBtn)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.OnToggleOutput, self.toggleOutputBtn)
        self.Bind(wx.EVT_BUTTON, self.OnPulse, self.pulseBtn)
        self.Bind(wx.EVT_BUTTON, self.OnAddRow, self.addRowBtn)
        self.Bind(wx.EVT_BUTTON, self.OnCleanRows, self.cleanRowsBtn)
        self.Bind(wx.EVT_BUTTON, self.OnOpenFile, self.openFileBtn)
        self.Bind(wx.EVT_BUTTON, self.OnSaveFile, self.saveFileBtn)
        self.Bind(wx.EVT_BUTTON, self.OnStart, self.startBtn)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.OnTogglePause, self.pauseBtn)
        self.Bind(wx.EVT_BUTTON, self.OnStop, self.stopBtn)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: FuncGenFrame.__set_properties
        self.SetTitle("pyFuncGen")
        self.pauseBtn.Enable(False)
        self.stopBtn.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: FuncGenFrame.__do_layout
        mainHsizer = wx.BoxSizer(wx.HORIZONTAL)
        mainVsizer = wx.BoxSizer(wx.VERTICAL)
        self.protocolOptnsSzr_staticbox.Lower()
        protocolOptnsSzr = wx.StaticBoxSizer(self.protocolOptnsSzr_staticbox, wx.HORIZONTAL)
        protocolCtrlsizer = wx.BoxSizer(wx.HORIZONTAL)
        self.protocolGridSzr_staticbox.Lower()
        protocolGridSzr = wx.StaticBoxSizer(self.protocolGridSzr_staticbox, wx.VERTICAL)
        gridCtrlsizer = wx.BoxSizer(wx.HORIZONTAL)
        self.ctrlBoxSzr_staticbox.Lower()
        ctrlBoxSzr = wx.StaticBoxSizer(self.ctrlBoxSzr_staticbox, wx.HORIZONTAL)
        manualCtrlSizer = wx.FlexGridSizer(4, 5, 1, 10)
        devCtrlsizer = wx.BoxSizer(wx.HORIZONTAL)
        devCtrlsizer.Add(self.devListRefreshBtn, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        devCtrlsizer.Add(self.deviceChoice, 1, wx.EXPAND, 0)
        devCtrlsizer.Add(self.connectBtn, 0, 0, 0)
        mainVsizer.Add(devCtrlsizer, 0, wx.EXPAND, 0)
        stageDispLabel = wx.StaticText(self.mainPnl, -1, "Stage")
        manualCtrlSizer.Add(stageDispLabel, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        manualCtrlSizer.Add(self.stageDisplay, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        manualCtrlSizer.Add(self.freqCtrlLabel, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        manualCtrlSizer.Add(self.freqCtrl, 1, wx.EXPAND | wx.ALIGN_CENTER_VERTICAL, 0)
        manualCtrlSizer.Add(self.applyBtn, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        timeDispLabel = wx.StaticText(self.mainPnl, -1, "Time remains")
        manualCtrlSizer.Add(timeDispLabel, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        manualCtrlSizer.Add(self.timeDisplay, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        amplCtrlLabel = wx.StaticText(self.mainPnl, -1, "Amplitude (Vpp)")
        manualCtrlSizer.Add(amplCtrlLabel, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        manualCtrlSizer.Add(self.amplCtrl, 1, wx.EXPAND | wx.ALIGN_CENTER_VERTICAL, 0)
        manualCtrlSizer.Add(self.toggleOutputBtn, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        manualCtrlSizer.Add(self.intervalDispLabel, 0, 0, 0)
        manualCtrlSizer.Add(self.intervalDisplay, 0, 0, 0)
        manualCtrlSizer.Add((20, 20), 0, 0, 0)
        manualCtrlSizer.Add(self.amplVrmsDisplay, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        manualCtrlSizer.Add((20, 20), 0, 0, 0)
        manualCtrlSizer.Add((20, 20), 0, 0, 0)
        manualCtrlSizer.Add((20, 20), 0, 0, 0)
        pulseCtrlLabel = wx.StaticText(self.mainPnl, -1, "Pulse Duration (ms)")
        manualCtrlSizer.Add(pulseCtrlLabel, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
        manualCtrlSizer.Add(self.pulseCtrl, 0, wx.EXPAND | wx.ALIGN_CENTER_VERTICAL, 0)
        manualCtrlSizer.Add(self.pulseBtn, 0, 0, 0)
        manualCtrlSizer.AddGrowableCol(1)
        manualCtrlSizer.AddGrowableCol(3)
        ctrlBoxSzr.Add(manualCtrlSizer, 1, 0, 0)
        mainVsizer.Add(ctrlBoxSzr, 0, wx.ALL | wx.EXPAND, 5)
        protocolGridSzr.Add(self.protocolGrid, 1, wx.EXPAND, 0)
        gridCtrlsizer.Add(self.addRowBtn, 1, wx.EXPAND, 0)
        gridCtrlsizer.Add(self.cleanRowsBtn, 1, wx.EXPAND, 0)
        gridCtrlsizer.Add(self.openFileBtn, 1, wx.EXPAND, 0)
        gridCtrlsizer.Add(self.saveFileBtn, 1, wx.EXPAND, 0)
        protocolGridSzr.Add(gridCtrlsizer, 0, wx.EXPAND, 0)
        mainVsizer.Add(protocolGridSzr, 1, wx.ALL | wx.EXPAND, 5)
        protocolCtrlsizer.Add(self.startBtn, 1, wx.EXPAND, 0)
        protocolCtrlsizer.Add(self.pauseBtn, 1, wx.EXPAND, 0)
        protocolCtrlsizer.Add(self.stopBtn, 1, wx.EXPAND, 0)
        mainVsizer.Add(protocolCtrlsizer, 0, wx.TOP | wx.EXPAND, 5)
        protocolOptnsSzr.Add((20, 20), 1, wx.EXPAND, 0)
        protocolOptnsSzr.Add(self.leaveOutPauseCb, 1, 0, 0)
        protocolOptnsSzr.Add(self.leaveOutFinishCb, 1, 0, 0)
        mainVsizer.Add(protocolOptnsSzr, 0, wx.ALL | wx.EXPAND, 5)
        self.mainPnl.SetSizer(mainVsizer)
        mainHsizer.Add(self.mainPnl, 1, wx.EXPAND, 0)
        self.SetSizer(mainHsizer)
        mainHsizer.Fit(self)
        self.Layout()
        # end wxGlade

    def OnDevListRefresh(self, event):  # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnDevListRefresh' not implemented!"
        event.Skip()

    def OnToggleConnect(self, event):  # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnToggleConnect' not implemented!"
        event.Skip()

    def OnApply(self, event):  # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnApply' not implemented!"
        event.Skip()

    def OnToggleOutput(self, event):  # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnToggleOutput' not implemented!"
        event.Skip()

    def OnPulse(self, event):  # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnPulse' not implemented!"
        event.Skip()

    def OnAddRow(self, event):  # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnAddRow' not implemented!"
        event.Skip()

    def OnCleanRows(self, event):  # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnCleanRows' not implemented!"
        event.Skip()

    def OnOpenFile(self, event):  # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnOpenFile' not implemented!"
        event.Skip()

    def OnSaveFile(self, event):  # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnSaveFile' not implemented!"
        event.Skip()

    def OnStart(self, event):  # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnStart' not implemented!"
        event.Skip()

    def OnTogglePause(self, event):  # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnTogglePause' not implemented!"
        event.Skip()

    def OnStop(self, event):  # wxGlade: FuncGenFrame.<event_handler>
        print "Event handler `OnStop' not implemented!"
        event.Skip()

# end of class FuncGenFrame
if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    MyFrame = FuncGenFrame(None, -1, "")
    app.SetTopWindow(MyFrame)
    MyFrame.Show()
    app.MainLoop()
