#----------------------------------------------------------------------
# This file was generated by C:\Python27\Scripts\img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

catalog = {}
index = []

App = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAABOUlEQVR4nO2VwY2FIBRFr+Yn"
    "vwcKsAEboA5rMQETa7AEG7ABd64oQLYm9jAbncUM5skHvpphZhaezfOhcm+uAsDNH5O4BvM8"
    "X2OKKqU23Yd9syiKqOLjOO76nQEpZVTxtwYAQAgRTbyqqpexFwO+B0Nwzi8Z8hoAACnloQnM"
    "c33fg3O+1XmeobVGlmVgjHnfT98JPJclWA0mBVO11pimCXVdB+cPGjgqDnwlQGuWZRiGAWVZ"
    "Bg3QT+BcAR9piueyOCvFToAxhqZpfLorvvegYAJGxFcpdgJ29XH4H/D1BjsBu14yQCN39ZRo"
    "CRwlSgL0m9Mfz5WCWf+h69MGXGZ8Pd24fNcu6HG8SikhhDi9FZ+h6zoopTbtnQEASezjuG3b"
    "BGQfoEQ/il1aP7YKrmKfhr+Zws3Nzc3/4BM6K6cq8ohI3QAAAABJRU5ErkJggg==")
index.append('App')
catalog['App'] = App
getAppData = App.GetData
getAppImage = App.GetImage
getAppBitmap = App.GetBitmap
getAppIcon = App.GetIcon

